version: '3'

includes:
  configure:
    taskfile: ./configure/Taskfile.yaml
    dir: ../
  install:
    taskfile: ./install/Taskfile.yaml
    dir: ../
  generate:
    taskfile: ./generate/Taskfile.yaml
    dir: ../

tasks:
  setup-env:
    desc: 'Set up the environment'
    cmds:
      - task: configure:env-file:create
      - task: configure:env-file:fill

  install:
    desc: 'Install applications and tools'
    cmds:
      - task: install:brew:backend
      - task: install:chrome:extensions
      - task: configure:git:setup
      - task: configure:tools:all
      - task: install:application:phpstorm
      - task: install:terminal:tools

  generate:
    desc: 'Generate required files'
    cmds:
      - task: generate:ssh-key

  setup:
    desc: 'Set up the working station'
    cmds:
      - task: generate
      - task: install
