version: '3'

includes:
  configure:
    taskfile: ./configure/Taskfile.yaml
    dir: ../
  install:
    taskfile: ./install/Taskfile.yaml
    dir: ../
  generate:
    taskfile: ./generate/Taskfile.yaml
    dir: ../