version: 3

tasks:
  all:
    desc: Configure all tools
    cmds:
      - task: docker
      - task: composer
      - task: npm
      - task: qlico
  docker:
    desc: Configure Docker Registry to use private GitLab registry
    cmds:
      - docker login gitlab.com:443 --username {{.GIT_USER_NAME}} --password {{.PROVISIONER_GITLAB_TOKEN}}
  composer:
    desc: Configure Composer to use private GitLab registry
    cmds:
      - composer config -g gitlab-token.gitlab.com {{.PROVISIONER_GITLAB_TOKEN}}
  npm:
    desc: Configure NPM to use private packages
    cmds:
      - clear
      - echo "Request your personal NPM token from your manager."
      - open open 'slack://channel?team=T291H298U&id=U5X4MJDB7'
      - 'echo "Enter your NPM token: "; read -s NPM_TOKEN; echo "export NPM_TOKEN=$NPM_TOKEN" >> ~/.zshrc'
  qlico:
    desc: Configure network interface used by Qlico (Docker)
    cmds:
      - echo 'alias qlico_dns="sudo ifconfig lo0 alias 10.254.254.254 255.255.255.0"' >> ~/.zshrc
