brew "docker"
brew "dnsmasq"
brew "git"
brew "go-task"
brew "k9s"
brew "mas"
brew "zsh"

cask "insomnia"
cask "iterm2"
cask "openvpn-connect"
cask "orbstack"
cask "phpstorm"

mas "LastPass", id: 926036361
mas "Sequel Ace", id: 1518036000
mas "Slack", id: 803453959
