version: '3'
tasks:
  extensions:
    desc: Install Chrome extensions
    cmds:
      - mkdir -p ~/Library/Application\ Support/Google/Chrome/External\ Extensions
      - cp -r ../extensions/chrome/* ~/Library/Application\ Support/Google/Chrome/External\ Extensions