version: "3"

tasks:
  tools:
    desc: Install terminal tools
    cmds:
      - task: oh-my-zsh
  oh-my-zsh:
    desc: Install Oh My Zsh
    cmds:
      - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    status:
      - test -d ~/.oh-my-zsh
  powerlevel10k:
    desc: Install ZSH Powerlevel10K plugin
    cmds:
      - brew install powerlevel10k
      - echo "source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme" >> ~/.zshrc
      - sed -i 's/^ZSH_THEME=.*$/ZSH_THEME=powerlevel10k\/powerlevel10k/' ~/.zshrc
    status:
      - test -f $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
