version: "3"

tasks:
  tools:
    desc: Install terminal tools
    cmds:
      - task oh-my-zsh
  oh-my-zsh:
    desc: Install Oh My Zsh
    cmds:
      - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    status:
      - test -d ~/.oh-my-zsh
      - test ! $(which zsh)
