version: 3

tasks:
  setup:
    desc: Setup the Git configuration
    cmds:
      - task: config
  config:
    desc: Configure Git
    cmds:
      - git config --global user.name "{{.FULL_NAME}}"
      - git config --global user.email "{{.USER_EMAIL}}"
      - git config --global core.editor "vim"
      - git config --global user.signingkey "~/.ssh/{{.USER_EMAIL}}"
      - git config --global commit.gpgSign true
      - git config --global tag.gpgSign true
      - git config --global gpg.format ssh
    status:
      - git config --global --get user.name
      - git config --global --get user.email
      - git config --global --get core.editor
      - git config --global --get user.signingkey
      - git config --global --get commit.gpgSign
      - git config --global --get tag.gpgSign
      - git config --global --get gpg.format
    deps:
      - task: setup-ssh
  setup-ssh:
    desc: Upload the SSH key to Gitlab
    cmds:
      - glab config --global set token {{.PROVISIONER_GITLAB_TOKEN}}
      - glab ssh-key add --title "Laptop Provisioner" --expires-at $(date -u -v+1y +"%Y-%m-%d") ~/.ssh/{{.USER_EMAIL}}.pub
    deps:
      - task: :env-file:fill-gitlab-token
      - task: ::generate:ssh-key

  remove-ssh:
    desc: Remove the SSH key from Gitlab
    cmds:
      - glab ssh-key delete $(glab ssh-key list --show-id | grep "Laptop Provisioner" | awk '{print $1}')
    status:
      - test -z "$(glab ssh-key list --show-id | grep "Laptop Provisioner")"
  refresh-authentication:
    desc: Refresh the SSH key and token for Gitlab
    cmds:
      - task: ::generate:refresh-ssh-key
      - task: remove-ssh
      - task: :env-file:reset-gitlab-token
      - task: setup-ssh
