version: 3

tasks:
  setup:
    desc: Setup the Git configuration
    cmds:
      - task: config
      - task: setup-ssh
  config:
    desc: Configure Git
    cmds:
      - git config --global user.name "{{.FULL_NAME}}"
      - git config --global user.email "{{.USER_EMAIL}}"
      - git config --global core.editor "vim"
      - git config --global user.signingkey "~/.ssh/{{.USER_EMAIL}}"
      - git config --global commit.gpgSign true
      - git config --global tag.gpgSign true
      - git config --global gpg.format ssh
    status:
      - git config --global --get user.name
      - git config --global --get user.email
      - git config --global --get core.editor
      - git config --global --get user.signingkey
      - git config --global --get commit.gpgSign
      - git config --global --get tag.gpgSign
      - git config --global --get gpg.format
    deps:
      - system:generate:ssh-key
  setup-ssh:
    desc: Upload the SSH key to Gitlab
    cmds:
      - glab config --global set token {{.GITLAB_TOKEN}}
      - glab ssh-key add --title "Laptop Provisioner" --expires-at $(date -u -v+1y +"%Y-%m-%d") ~/.ssh/{{.USER_EMAIL}}.pub
    deps:
      - task: ::generate:ssh-key
      - task: :env-file:fill-gitlab-token
