version: '3'
tasks:
  backend:
    prompt: 'Install Homebrew packages for backend development?'
    desc: Installing Homebrew packages for backend development
    cmds:
      - brew bundle install --file=../darwin/Brewfile.backend