version: 3

tasks:
  create:
    desc: Create the .env file
    cmds:
      - touch .env
    status:
      - test -f .env
  fill:
    desc: Fill the .env file
    cmds:
      - task: fill-user-email
      - task: fill-full-name
      - task: fill-gitlab-token
  fill-full-name:
    cmds:
      - 'clear; read -p "Enter your full name (Like: John Doe): " FULL_NAME; echo "FULL_NAME=$FULL_NAME" >> .env'
    status:
      - grep -q "FULL_NAME=" .env
  fill-user-email:
    cmds:
      - 'clear; read -p "Enter your work email address: " USER_EMAIL; echo "USER_EMAIL=$USER_EMAIL" >> .env'
    status:
      - grep -q "USER_EMAIL=" .env
  fill-gitlab-token:
    cmds:
      - 'clear'
      - 'echo "Please visit https://gitlab.com/-/user_settings/personal_access_tokens and create a new token with the following scopes: api"'
      - 'open -a "Google Chrome" "https://gitlab.com/-/user_settings/personal_access_tokens?name=Laptop+Provisioner&scopes=api"'
      - 'echo "Enter your GitLab token: "; read -s GITLAB_TOKEN; echo "GITLAB_TOKEN=$GITLAB_TOKEN" >> .env'
    status:
      - grep -q "GITLAB_TOKEN=" .env
  reset-gitlab-token:
    cmds:
      - 'sed -i "" "/GITLAB_TOKEN=/d" .env'
      - task: fill-gitlab-token