version: 3

tasks:
  create:
    desc: Create the .env file
    cmds:
      - touch .env
    status:
      - test -f .env
  fill:
    desc: Fill the .env file
    cmds:
      - task: fill-user-email
      - task: fill-full-name
  fill-full-name:
    cmds:
      - 'clear; read -p "Enter your full name (Like: John Doe): " FULL_NAME; echo "FULL_NAME=$FULL_NAME" >> .env'
    status:
      - grep -q "FULL_NAME=" .env
  fill-user-email:
    cmds:
      - 'clear; read -p "Enter your work email address: " USER_EMAIL; echo "USER_EMAIL=$USER_EMAIL" >> .env'
    status:
      - grep -q "USER_EMAIL=" .env