version: '3'
includes:
  brew:
    taskfile: ./brew/Taskfile.yaml
    dir: ../../
  chrome:
    taskfile: ./chrome/Taskfile.yaml
    dir: ../../
  terminal:
    taskfile: ./terminal/Taskfile.yaml
    dir: ../../
  apps:
    taskfile: ./application/Taskfile.yaml
    dir: ../../
